spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
  
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always

securt-kit:
  encrypt:
    enabled: true
    algorithm: AES
    key: test-secret-key-32-chars-long-enough
    patternType: DB
    fields:
      user:
        - phone
        - email
        - id_card
        - age
      orders:
        - customer_name
        - customer_phone
        - customer_email
        - delivery_address
    scanEntityPackages:
      - com.chu7.securtkit.test.entity

logging:
  level:
    com.chu7.securtkit: DEBUG
    org.apache.ibatis: DEBUG
    com.baomidou.mybatisplus: DEBUG 